### ISSUE TITLE
Parser for input data matrix

### ISSUE THREAD

**Issue by jdopazob** [babelomics/pathact#1]
Data must be in tab-delimited format with samples in rows and gene/probe/protein in rows. First colums are gene/probe/protein identifiers. Parser must verify that the format is correct and the identifiers are the expected ones.

**Comment by frasator** [comment]
A new documentation page has been created with a more detailed information about input file format.
http://pathact.babelomics.org/doc/doku.php?id=data_matrix_expression_file

The link can be found now on the launch form and inside the upload panel.

A parser has been implemented in the upload panel to detect errors before upload.
